// All action type classes should have an ID here

typedef enum
{
	ACTION = 0,
	STAND_ACTION,
	PAIN_ACTION,
	DEATH_ACTION,
	DEATHCORPSE_ACTION,
	DEATHARMOR_ACTION,
	ENDSCRIPT_ACTION,
	WALK_ACTION,
	DOG_WALK_ACTION,
	JUMP_ACTION,
	FALL_ACTION,
	SURRENDER_ACTION,
	CAPTURE_ACTION,
	SHOOT_ATTACK_ACTION,
	RUNNING_MELEE_ATTACK_ACTION,

	HELI_ACTION,
	HELIMOVE_ACTION,
	HELIFACE_ACTION,
	HELIATTACK_ACTION,
	HELIDEATH_ACTION,
	SNOWCAT_ACTION,
	TANK_ACTION,
};

