
#include "g_local.h"
#include "ai_private.h"

//	ghoulSeqName								velScale minTurn														bbox					playpos	bodyposition
//								suggested_action	maxTurn		actionFlags

mmove_t	ScriptReleaseMove[MMOVE_SCRIPT_SIZE]=
{
	{"std_istand_n_a_n",	ACTCODE_SCRIPTRELEASE,	0,	0,	0,		0,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN}
};

mmove_t MMoves[MMOVE_HUMAN_SIZE]=
{
	//0
	{"std_istand_n_a_n",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_wnormal_n_pk_a",		ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_r_n_pk_n",			ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_f_n_p_2",				ACTCODE_ATTACK,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rgunup_n_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//5
	{"std_stoknees_2bk_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_jupto_n_a_a",			ACTCODE_JUMP,	0,	0,	0,		ACTFLAG_JUMPTOGROUND2|ACTFLAG_RHANDOPEN,				BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fattitude_n_p_a",		ACTCODE_ATTACK,	1,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wattitude_n_pk_a",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jdrop_n_a_a",			ACTCODE_FALL,	1,	5,	-5,		ACTFLAG_RHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//10
	{"std_raim_n_p_n",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raim_n_p_2",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcrouch_dwn_pk_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_xcrouch_mid_pk_a",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_f_fwd_p_2",			ACTCODE_ATTACK,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
																
	//15
	{"cch_xcrouch_up_pk_a",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ilooking_n_a_a",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_istretch_n_a_a",		ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_sblown_2bk_n_n",		ACTCODE_DEATH,	1,	0,	-0,		ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_rafraid_n_n_n",		ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//20
	{"cch_a_fwd_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_p_cb",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_f_fwd_p_cb",			ACTCODE_ATTACK,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sdance_n_n_n",		ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//25
	{"std_shead_2frnt_n_n",		ACTCODE_DEATH,	1,	0,	  0,	0,														BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"std_f_fwd_p_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_slegrt_2bk_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_sleglt_2bk_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_sshoulder_rt_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,					BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},

	//30
	{"std_sshoulder_lt_n_n",	ACTCODE_DEATH,	1,	 0,	  0,	ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,					BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"lb_pgeneric_n_n_n",		ACTCODE_DEATH,	1,	 0,	  0,	ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pholdleg_rt_n_n",		ACTCODE_DEATH,	1,	 0,	  0,	ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pholdleg_lt_n_n",		ACTCODE_DEATH,	1,	 0,	  0,	ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"cch_sdead_2bk_n_n",		ACTCODE_DEATH,	1,   0,	  0,	ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},

	//35
	{"std_ashuffle_n_p_2",		ACTCODE_STAND,	1,	30,	-30,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ashuffle_n_p_a",		ACTCODE_STAND,	1,	30,	-30,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_f_fwd_m_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_ms_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_istand_n_mrs_2",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
																																		
	//40																																
	{"std_ilooking_n_mrs_2",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_istretch_n_mrs_2",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_wpatrol_n_mrs_2",		ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_icleangun2_n_pk_n",	ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_imonitorup_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
																																		
	//45																																
	{"std_italk_n_a_n",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest1_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest2_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest3_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_iwipebrow_n_a_n",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},

	//50
	{"std_xalarmpush_n_a_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xyellpoint_fwd_a_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xyellwave_bk_a_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jdive2prone_n_a_n",	ACTCODE_MOVE,	1,	 0,	  0,	ACTFLAG_FULLANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_xboomcrouch_n_a_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
																																		
	//55
	{"std_xtumble_2frnt_n_n",	ACTCODE_DEATH,	1,	0,	  0,	0,														BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"std_wcarry1_n_n_n",		ACTCODE_MOVE,	1,	30,	-30,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wpatrol_n_mrs_2",		ACTCODE_MOVE,	1,	30,	-30,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_r_n_mrs_2",			ACTCODE_MOVE,	1,	25,	-25,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_f_fwd_s_2",			ACTCODE_ATTACK,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//60
	{"cch_f_fwd_r_2",			ACTCODE_ATTACK,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_a_fwd_ms_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_a_fwd_r_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_fcornerpeak_lt_m_2",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fcornerpeak_rt_m_2",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//65
	{"std_fcornerpeak_lt_p_a",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fcornerpeak_rt_p_a",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wbcksignal_n_n_n",	ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_BACKUP,											BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wturn90_lt_pk_n",		ACTCODE_MOVE,	1,	1,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_WALKTURN},
	{"std_wturn90_rt_pk_n",		ACTCODE_MOVE,	1,	2,	-1,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_WALKTURN},

	//70
	{"std_wturn90_lt_mrs_2",	ACTCODE_MOVE,	1,	1,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_WALKTURN},
	{"std_wturn90_rt_mrs_2",	ACTCODE_MOVE,	1,	2,	-1,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_WALKTURN},
	{"lb_pholdlegto_rt_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pholdlegto_lt_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pgenericto_n_n_n",		ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},

	//75
	{"lb_pholdlegdie_rt_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pholdlegdie_lt_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_pgenericdie_n_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_waimstraf_lt_l_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,						BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waimstraf_rt_l_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,		BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},

	//80
	{"std_wbackaim_n_l_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_w_n_l_2",				ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xatkpause1_n_mrs_2",	ACTCODE_STAND,	0,	30,	-30,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xatkpause2_n_mrs_2",	ACTCODE_STAND,	0,	30,	-30,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xatkpause1_n_pk_n",	ACTCODE_STAND,	0,	30,	-30,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//85
	{"std_xatkpause2_n_pk_n",	ACTCODE_STAND,	0,	30,	-30,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"lb_sautofire_loop_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_sautofire_end_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"cch_f_fwd_m_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_wturn180_lt_mrs_2",	ACTCODE_MOVE,	1,	0,	0,		/*ACTFLAG_MATCHABS|*/ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//90
	{"std_f_fwd_s_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xopendoor_n_a_n",		ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_f_fwd_r_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_r_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcrouch_dwn_mrs_2",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//95
	{"cch_xcrouch_up_mrs_2",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raimstraf_lt_p_cbn",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raimstraf_rt_p_cbn",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raimstraf_lt_mrs_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raimstraf_rt_mrs_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//100
	{"std_raim_n_mrs_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ashuffle_n_ms_2",		ACTCODE_STAND,	1,	30,	-30,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ashuffle_n_r_2",		ACTCODE_STAND,	1,	30,	-30,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ialert_n_p_n",		ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ialertlk_lt_p_n",		ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},

	//105
	{"std_xroll_rt_a_a",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_xroll_lt_a_a",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_ialerttrn_rt_p_n",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ialert_n_mrs_2",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_raimstraf_lt_l_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//110
	{"std_ialertlk_rt_mrs_2",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ialerttrn_lt_mrs_2",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_tgrenade_n_a_n",		ACTCODE_ATTACK,	1,	2,	-2,		ACTFLAG_FULLANIM|ACTFLAG_GRENADE,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sgroin_2side_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"std_sthroat_2side_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},

	//115
	{"std_fautosweep_n_m_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_italk_n_mrs_2",		ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest1_n_mrs_2",	ACTCODE_STAND,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest2_n_mrs_2",	ACTCODE_STAND,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_italkgest3_n_mrs_2",	ACTCODE_STAND,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},

	//120
	{"prn_a_n_mrs_2",			ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"prn_a_n_mrs_2",			ACTCODE_ATTACK,	0,	0,	0,		ACTFLAG_OPTATTACK,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"lf_sautofire_loop_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,					BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"lf_sautofire_end_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"std_xafraidshake_n_n_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//125
	{"std_sgunfromhand_n_n_n",	ACTCODE_PAIN,	0,	10,	-10,	ACTFLAG_RHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jrun_fwd_a_a",		ACTCODE_JUMP,	1,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"RUBBISHWASstd_xjitter_n_n_n",		ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN|ACTFLAG_LOOPANIM,	BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"RUBBISHWASstd_xjitter2_n_n_n",		ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN|ACTFLAG_LOOPANIM,	BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_r_dwnst_pn_a",		ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//130
	{"std_r_upst_pn_a",			ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_sonknees_2frnt_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"cch_xonknees_n_n_n",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_iturnvalve_frm_n_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_iturnvalve_n_n_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	
	//135
	{"std_iturnvalve_to_n_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_mkicklow_n_a_a",		ACTCODE_STAND,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_mpistolwhip_n_p_n",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sinback_2frnt_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"ls_xgetkicked_n_n_n",		ACTCODE_PAIN,	0,	0,	0,	ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},

	//140
	{"si_xbywall_n_n_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_SIT,		0,		BODYPOS_UNKNOWN},
	{"std_sstumble_2bk_p_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_wpush_n_n_n",			ACTCODE_MOVE,	1,	30,	-30,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xkickdoor_n_a_a",		ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xyellatyou_n_a_a",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//145
	{"std_ileanlook_frm_pk_n",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ileanlook_mid_pk_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ileanlook_to_pk_n",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_jdown_n_a_a",			ACTCODE_JUMP,	1,	0,	0,		ACTFLAG_JUMPTOGROUND2,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_xcchcower_mid_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//150
	{"cch_xcchcower2_mid_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_waimstraf_lt_ms_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waimstraf_lt_r_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waimstraf_lt_p_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_LEFTSTRAFE,						BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waimstraf_rt_ms_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},

	//155
	{"std_waimstraf_rt_r_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waimstraf_rt_p_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waim_fwd_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waim_fwd_r_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_waim_fwd_ms_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},

	//160
	{"std_wbackaim_n_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_wbackaim_n_r_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_wbackaim_n_ms_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_sunhurt_fwd_pk_n",	ACTCODE_PAIN,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sunhurt_fwd_mrs_2",	ACTCODE_PAIN,	0,	10,	-10,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//165
	{"std_sunhurt_bk_pk_n",		ACTCODE_PAIN,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sunhurt_bk_mrs_2",	ACTCODE_PAIN,	0,	10,	-10,	ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_pblinded_to_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_BLINDED},
	{"std_pblinded_loop_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_BLINDED},
	{"std_pblinded_frm_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//170
	{"std_ishift_n_a_n",		ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xstartled_n_a_a",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_l_n_p_2",				ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_l_n_ms_2",			ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sleg_rt_n_n",			ACTCODE_PAIN,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},

	//175
	{"std_sleg_lt_n_n",			ACTCODE_PAIN,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_LLEGHURT},
	{"std_phop_rt_n_n",			ACTCODE_PAIN,	0,	5,	-5,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_phop_lt_n_n",			ACTCODE_PAIN,	0,	5,	-5,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_LLEGHURT},
	{"std_plimp_rt_n_n",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_plimp_lt_n_n",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_LLEGHURT},

	//180
	{"std_l_n_r_2",				ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcchcower_dwn_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_rbackaim_n_mrs_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_BACKUP,		BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rbackaim_n_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sarm_rt_n_n",			ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},

	//185
	{"std_sarm_lt_n_n",			ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_parm_rt_n_n",			ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_parm_lt_n_n",			ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_xdontshoot_n_a_n",	ACTCODE_STAND,	0,	5,	-5,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xfearwave_n_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//190
	{"std_r_dwnst_mrs_2",		ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_r_upst_mrs_2",		ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_paim_n_a_n",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_LLEGHURT},
	{"std_paim_n_a_n",			ACTCODE_ATTACK,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_OPTATTACK,					BBOX_PRESET_STAND,		0,		BODYPOS_LLEGHURT},
	{"cch_xcchcower_up_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN|ACTFLAG_FULLANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//195
	{"std_l_n_p_n",				ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sviolent_n_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"prn_xcoverhead_to_a_a",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"prn_xcoverhead_n_a_a",	ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_schest_2frnt_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},

	//200
	{"std_sgut_2side_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"std_snervegun_2bck_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_icleangun2_n_mrs_2",	ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_imonitorup2_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_itouchnuts_n_a_n",	ACTCODE_STAND,	0,	20,	-20,	0,														BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},

	//205
	{"std_ismoke_frm_a_n",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ismoke_n_a_n",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ismoke_to_a_n",		ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_wjog_n_mrs_2",		ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wjoggundwn_n_p_2",	ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//210
	{"std_wjoggunup_n_p_a",		ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wpushcart_n_n_n",		ACTCODE_MOVE,	1,	30,	-30,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fautosweep_n_pm_a",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fgangbanger_n_m_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fswatstyle_fwd_m_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//215
	{"std_fviolent_dwn_m_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fviolent_dwn_p_n",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FIREFROMGUN,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_mninjakick_n_a_b",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_mriflebutt_n_mrs_2",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sfallfwd_2frnt_n_n",	ACTCODE_FALL,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},

	//220
	{"std_sstumble_2frnt_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},
	{"std_xchoke_n_n_n",		ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xdance_n_n_n",		ACTCODE_STAND,	1,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_xgoprone_n_a_a",		ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_xladder_dwn_a_a",		ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//225
	{"std_xladder_up_a_a",		ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xrolltocch_fwd_a_a",	ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_xstumble_n_a_a",		ACTCODE_STAND,	1,	10,	-10,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"si_isit_n_a_a",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_SIT,		0,		BODYPOS_IDLE},
	{"si_xalertstand_up_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//230
	{"prn_xfalling_n_n_n",		ACTCODE_FALL,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"prn_xfallland_n_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_LAYFRONT,		0,		BODYPOS_UNKNOWN},
	{"prn_xtostand_n_a_a",		ACTCODE_STAND,	1,	3,	-3,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_raim_fwd_mrs_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_raim_fwd_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//235
	{"lb_pcrawl_bk_p_n",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM|ACTFLAG_MATCHANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK, 0,	BODYPOS_UNKNOWN},
	{"lb_xleanupshoot_n_p_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"cch_f_fwd_l_2",			ACTCODE_ATTACK,	0,	10,	-10,	0,														BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_raim_n_l_2",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_tlobgrenade_n_a_n",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//240
	{"a4_cscramble_n_a_n",		ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"prn_c_n_a_2",				ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_a_up_mrs_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK|ACTFLAG_LHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_up_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_up_l_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//245
	{"std_sonfire_2bk_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_mslash_n_kp_n",		ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_mslash_n_kp_n",		ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0.6f,		BODYPOS_UNKNOWN},
	{"std_echokeknees_to_n_n",	ACTCODE_STAND,	1,	0,	  0,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_echokeknees_n_n_n",	ACTCODE_STAND,	1,	0,	  0,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//250
	{"cch_xcrouch_up_l_2",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_raimstraf_rt_l_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_RIGHTSTRAFE,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcrouch_dwn_l_2",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_r_dwnst_l_2",			ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_r_upst_l_2",			ACTCODE_MOVE,	1,	40,	-40,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//255
	{"std_raim_n_l_2",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rbackaim_n_l_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM|ACTFLAG_BACKUP,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jstraitup_up_l_2",	ACTCODE_JUMP,	0,	0,	0,		ACTFLAG_RHANDOPEN,										BBOX_PRESET_STAND,		0.8f,		BODYPOS_UNKNOWN},
	{"std_waim_fwd_l_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_OPTATTACK|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"std_l_n_l_2",				ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//260
	{"std_ashuffle_n_l_2",		ACTCODE_STAND,	1,	30,	-30,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_dwn_l_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_l_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_f_fwd_l_2",			ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_echokedeath_n_n_n",	ACTCODE_DEATH,	1,	0,	  0,	ACTFLAG_FULLANIM,										BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},

	//265
	{"std_selectrocute_n_n_n",	ACTCODE_STAND,	1,	0,	  0,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eoffladder_up_a_n",	ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_epounddoor_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jstraitup_up_a_a",	ACTCODE_JUMP,	0,	0,	0,		ACTFLAG_RHANDOPEN,										BBOX_PRESET_STAND,		0.8f,		BODYPOS_UNKNOWN},
	{"cch_a_fwd_l_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_LHANDOPEN,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//270
	{"cch_raim_fwd_mrs_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_REVERSEANIM,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_raim_fwd_p_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_REVERSEANIM,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_ebustglass_n_mrs_2",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_efliptable_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_epushbuttons_n_n_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_RHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//275
	{"std_epushcrate_n_a_n",	ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_esignalalarm_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_etyping_n_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewall2walk_n_mrs_2",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewall2walk_n_pk_n",	ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//280
	{"std_ewallidle_n_mrs_2",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewallidle_n_pk_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewalllook_lt_mrs_2",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewalllook_lt_pk_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewalllook_rt_mrs_2",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//285
	{"std_ewalllook_rt_pk_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewrenchh_frm_n_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewrenchh_n_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewrenchh_to_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewrenchv_frm_n_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//290
	{"std_ewrenchv_n_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewrenchv_to_n_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ecomehere_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ipiss_n_a_a",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM|ACTFLAG_PISS,			BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_athreat_dwn_p_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//295
	{"std_athreat_fwd_p_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_athreatyel_dwn_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_athreatyel_fwd_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eexaminewall_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jbackflip_n_p_n",		ACTCODE_JUMP,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_BACKUP,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},


	//300 will this nightmare never end?
	{"std_erageshoot_n_p_n",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_esabremock_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rtostop_n_pk_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_etalkboth_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalk_n_a_n",			ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},

	//305
	{"std_eheadnod_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eheadshake_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ejumprail_n_a_n",		ACTCODE_JUMP,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wtostop_n_pk_a",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_espin180_lt_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//310
	{"std_espin180_rt_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_etorun_n_p_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ilean_n_p_n",			ACTCODE_STAND,	1,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_etalkright_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_eclimbledg_dwn_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//315
	{"std_eclimbledg_mid_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_eclimbledge_up_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_edropgrenade_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_efalldeath_n_n_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_efallimpact_n_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//320
	{"std_efrmshadow_n_mrs_2",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_efrmshadow_n_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ehandtalk_frm_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_ehandtalk_n_p_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_ehandtalk_to_mrs_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},

	//325
	{"std_ehandtalk_to_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_ehandtalk_frm_mrs_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_eheadset_frm_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eheadset_mid_p_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eheadset_to_p_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//330
	{"std_esalute_frm_mrs_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_esalute_n_mrs_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_esalute_to_mrs_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_etalkleft_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalklklt_frm_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},

	//335
	{"std_etalklklt_mid_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalklklt_to_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalklkrt_frm_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalklkrt_mid_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_etalklkrt_to_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},

	//340
	{"std_etorun_n_mrs_2",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eturn90_lt_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eturn90_rt_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_igunup_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_ronfire_n_n_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//345
	{"std_ronfiretodth_n_n_n",	ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rtostop_n_mrs_2",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_edropcrouch_n_a_a",	ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_trun_n_a_n",			ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_w_n_pn_n",			ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//350
	{"std_wcarry2_n_n_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wtalk_lt_mrs_2",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"a4_cscramble_n_a_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"cch_enodleft_n_a_a",		ACTCODE_STAND,	1, 0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_enodright_n_a_a",		ACTCODE_STAND,	1, 0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//355
	{"cch_escantalk_lt_a_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_escantalk_rt_a_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_iready_n_a_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_IDLE},
	{"std_echokeshoot_n_a_n",	ACTCODE_ATTACK,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_hleanltsht_to_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANLEFT},

	//360
	{"std_hleanltsht_to_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANLEFT},
	{"std_hleanltsht_mid_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANLEFT},
	{"std_hleanltsht_mid_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANLEFT},
	{"std_hleanltsht_frm_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_hleanltsht_frm_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//365
	{"std_hleanrtsht_to_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"std_hleanrtsht_to_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"std_hleanrtsht_mid_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"std_hleanrtsht_mid_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"std_hleanrtsht_frm_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//370
	{"std_hleanrtsht_frm_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_hleanltsht_to_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANLEFT},
	{"cch_hleanltsht_to_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANLEFT},
	{"cch_hleanltsht_mid_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANLEFT},
	{"cch_hleanltsht_mid_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANLEFT},

	//375
	{"cch_hleanltsht_frm_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_hleanltsht_frm_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_hleanrtsht_to_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"cch_hleanrtsht_to_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"cch_hleanrtsht_mid_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANRIGHT},

	//380
	{"cch_hleanrtsht_mid_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_PLAYERLEANRIGHT},
	{"cch_hleanrtsht_frm_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_hleanrtsht_frm_l_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_etalk_frm_a_n",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_TALKING},
	{"std_etalk_to_a_n",		ACTCODE_STAND,	0, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_TALKING},

	//385
	{"std_mswipe_n_kp_b",		ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rswipe_n_k_n",		ACTCODE_MOVE,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_rswipe_n_k_n",		ACTCODE_MOVE,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_LHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_jdrop_to_a_n",		ACTCODE_JUMP,	1,	0,	0,		ACTFLAG_FULLANIM,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_athreatsht_dwn_p_n",	ACTCODE_ATTACK,	1,	0,	0,		ACTFLAG_FULLANIM,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//390
	{"std_a_dwn_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK|ACTFLAG_LHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_a_dwn_mrs_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK|ACTFLAG_LHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"RUBBISHWAS std_xcock_n_s_2",			ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_xladderfrm_up_a_a",	ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_etostand_n_a_n",		ACTCODE_STAND,	1,  0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//395
	{"std_ininja_n_p_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_xhandspring_fwd_a_n",	ACTCODE_MOVE,	1,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcock_n_s_2",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcock_n_r_2",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_xcock_n_s_2",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//400
	//special non-death sblown for armored guys
	{"std_sblown_2bk_n_n",		ACTCODE_PAIN,	1,	0,	-0,		ACTFLAG_RHANDOPEN|ACTFLAG_LHANDOPEN,					BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lb_xgetup_n_a_n",			ACTCODE_STAND,	1,	3,	-3,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_raim_n_l_2",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_REVERSEANIM,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_r_n_pk_n",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_r_n_pk_n",			ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM|ACTFLAG_REVERSEANIM,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//405
	{"std_egangsalute_n_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_wbackwards_n_a_n",	ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ssabredeath_bk_n_n",	ACTCODE_DEATH,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_wstealth_n_pk_n",		ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jthrowstar_fwd_a_n",	ACTCODE_JUMP,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//410
	{"prn_a_n_a_2",				ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_PRONE,		0,		BODYPOS_UNKNOWN},
	{"std_eyell_n_a_n",			ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ialertlk_rt_mrs_2",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_epushbuttonh_n_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_rdynamic_n_a_n",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//415 -- and Dan thought this was ugly at 300...
	{"std_ietalkpose_n_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},
	{"std_frapidsweep_lt_p_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ialerttrn_lt_p_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_esuprise90_lt_a_n",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fautosweep_up_m_2",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//420
	{"si_ewallidle_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_ALWAYSPRONE|ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"si_ewalltalk_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_ALWAYSPRONE|ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_etoaim_n_p_2",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"si_ewallfear_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_ALWAYSPRONE|ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_esalute_to_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//425
	{"std_esalute_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"std_esalute_frm_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_esalutations_n_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eclimbshaft_n_a_n",	ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_w_n_a_n",				ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LOOPANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//430
	{"cch_ewalk2cch_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_etalk_dwn_p_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_italkpose_up_a_n",	ACTCODE_STAND,	0,  0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},
	{"cch_italkpose_dwn_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_etalk_up_a_n",		ACTCODE_STAND,	0,  0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_IDLE},

	//435
	{"cch_eheadnod_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_ecch2walk_n_a_n",		ACTCODE_STAND,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_wfast_n_a_n",			ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_erageidle_n_p_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ietalkpose_rt_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_TALKING},

	//440
	{"std_smicro_n_n_n",		ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"std_ebooklook_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ebookscan_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_eheadset_frm_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_eheadset_mid_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//445
	{"std_w_n_mrs_2",			ACTCODE_MOVE,	1, 20,-20,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_edkraim_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_ehawkknees_n_n_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_edkraimtalk_n_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_edkrfirelk_rt_a_n",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//450
	{"cch_ehawkdeath_n_n_n",	ACTCODE_DEATH,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"cch_ehawkkneetlk_n_n_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_ehawkcrouch_n_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM,										BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_eheadset_to_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"lb_eslide_n_pk_n",		ACTCODE_MOVE,	1,	5,	-5,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},

	//455
	{"std_igunuplook_n_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_frapid_n_p_2",		ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_edkraimlk_fwd_a_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_hsignalgo_n_a_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_hsignalstop_n_a_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//460
	{"std_htaunt_n_a_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ewhirl_rt_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,	BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fsweepup_frm_a_a",	ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_fsweepup_to_a_a",		ACTCODE_STAND,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xtakecover_n_a_n",	ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//465
	{"std_tstar_fwd_a_n",		ACTCODE_ATTACK,	1,	2,	-2,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_sarmunhurt_lt_a_n",	ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_sarmunhurt_rt_a_n",	ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_slegunhurt_lt_a_n",	ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},
	{"std_slegunhurt_rt_a_n",	ACTCODE_PAIN,	0,	0,	0,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_RLEGHURT},

	//470
	{"std_jthrowstar_bk_a_n",	ACTCODE_JUMP,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN|ACTFLAG_BACKUP,		BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_esabrebluff_n_a_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_eautosweep_n_pm_a",	ACTCODE_ATTACK,	0,	10,	-10,	ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_tknife_n_k_a",		ACTCODE_ATTACK,	1,	2,	-2,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_tgrenade_n_a_n",		ACTCODE_ATTACK,	1,	2,	-2,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0.9f,	BODYPOS_UNKNOWN},

	//475
	{"cch_a_fwd_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK|ACTFLAG_LHANDOPEN,					BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_a_fwd_p_2",			ACTCODE_STAND,	0,	20,	-20,	ACTFLAG_OPTATTACK|ACTFLAG_LHANDOPEN,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xhandspring_bk_a_n",	ACTCODE_MOVE,	1,	2,	-2,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_soutwindow_n_a_n",	ACTCODE_MOVE,	1,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_xcrouch_dwn_p_2",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//480
	{"std_tunder_n_a_n",		ACTCODE_ATTACK,	1,	2,	-2,		ACTFLAG_FULLANIM,										BBOX_PRESET_STAND,		0.9f,	BODYPOS_UNKNOWN},
	{"std_xcrouch_dwn_p_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_wfire_fwd_ms_2",		ACTCODE_MOVE,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,	BBOX_PRESET_STAND,		0,		BODYPOS_AIMWALK},
	{"cch_afire_fwd_ms_2",		ACTCODE_ATTACK,	1,	20,	-20,	ACTFLAG_LHANDOPEN|ACTFLAG_LOOPANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_epushover_n_pk_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//485
	{"std_lrun_bk_p_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_fwd_p_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_lt_p_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_rt_p_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_bk_l_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//490
	{"std_lrun_fwd_l_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_lt_l_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_rt_l_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_bk_ms_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_fwd_ms_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//495
	{"std_lrunstraf_lt_ms_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_rt_ms_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_bk_r_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrun_fwd_r_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lrunstraf_lt_r_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//500
	{"std_lrunstraf_rt_r_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_bk_p_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_fwd_p_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_lt_p_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_rt_p_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//505
	{"std_lwalk_bk_l_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_fwd_l_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_lt_l_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_rt_l_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_bk_ms_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//510
	{"std_lwalk_fwd_ms_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_lt_ms_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_rt_ms_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_bk_r_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalk_fwd_r_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//515
	{"std_lwalkstraf_lt_r_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_lwalkstraf_rt_r_2",	ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_l_fwd_p_2",			ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_l_fwd_l_2",			ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_l_fwd_ms_2",			ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//520
	{"cch_l_fwd_r_2",			ACTCODE_STAND,	0,	2,	-2,		ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_bk_p_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_fwd_p_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_bk_l_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_fwd_l_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},

	//525
	{"cch_lrun_bk_ms_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_fwd_ms_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_bk_r_2",			ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"cch_lrun_fwd_r_2",		ACTCODE_MOVE,	0,	2,	-2,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_FULLANIM,						BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"std_emerchall_n_a_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//530
	{"std_emerchone_n_a_a",		ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_iemerchant_n_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_emerchwave_rt_a_a",	ACTCODE_STAND,	1, 0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_emerchtalk_n_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_emerchwave_lt_a_a",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_FULLANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//535
	{"std_ebeg_n_a_a",			ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN,						BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"cch_xcchcower_n_a_n",		ACTCODE_STAND,	0,	0,	0,		ACTFLAG_LOOPANIM|ACTFLAG_LHANDOPEN|ACTFLAG_RHANDOPEN,					BBOX_PRESET_CROUCH,		0,		BODYPOS_UNKNOWN},
	{"lb_sautofire_end_n_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},
	{"lf_sautofire_end_n_n",	ACTCODE_STAND,	0,	0,	0,		ACTFLAG_ALWAYSPRONE,									BBOX_PRESET_LAYBACK,	0,		BODYPOS_UNKNOWN},

//keep this move at the end of the list please!!! pathcorners will know the list is finished when they hit it!
	{"",						ACTCODE_STAND,	0,	0,	0,		0,														BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

};

mmove_t MDogMoves[MMOVE_DOG_SIZE]=
{
	//0
	{"std_ibark_n",				ACTCODE_STAND,	0,		10,	-10,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ipant_n",				ACTCODE_STAND,	0,		10,	-10,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_r_n",					ACTCODE_MOVE,	1.1,	20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_stoside_rt",			ACTCODE_DEATH,	1,		0,	0,	0,														BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"std_w_n",					ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//5
	{"unused",					ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jattack_n",			ACTCODE_ATTACK,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wsniff_n",			ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_jattack_n",			ACTCODE_ATTACK,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0.4f,	BODYPOS_UNKNOWN},
	{"std_stumble_rt",			ACTCODE_DEATH,	1.0,	0,	0,	0,														BBOX_PRESET_LAYFRONT,	0,		BODYPOS_UNKNOWN},

	//10
	{"sit_i_n",					ACTCODE_STAND,	0,		10,	-10,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"sit_itostand_n",			ACTCODE_STAND,	1.0,	10,	-10,	0,													BBOX_PRESET_STAND,		0.0f,	BODYPOS_UNKNOWN},
	{"std_itosit_n",			ACTCODE_STAND,	1.0,	10,	-10,	0,													BBOX_PRESET_STAND,		0.0f,	BODYPOS_UNKNOWN},
	{"std_wsniff_frm",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wsniff_to",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//15
	{"std_wlooklt_frm",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wlooklt_n",			ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wlooklt_to",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wlookltrt_n",			ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_MATCHANIM,									BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wlookrt_frm",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},

	//20
	{"std_wlookrt_n",			ACTCODE_MOVE,	1,		20,	-20,	ACTFLAG_LOOPANIM|ACTFLAG_MATCHANIM,					BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_wlookrt_to",			ACTCODE_MOVE,	1,		20,	-20,	0,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"sid_prdl_rt",				ACTCODE_DEATH,	0,		0,	  0,	ACTFLAG_ALWAYSPRONE,								BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"sid_prdl2_rt",			ACTCODE_DEATH,	0,		0,	  0,	ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,				BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"sid_prdl3_rt",			ACTCODE_DEATH,	0,		0,	  0,	ACTFLAG_LOOPANIM|ACTFLAG_ALWAYSPRONE,				BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},

	// 25
	{"std_sblown_2bk",			ACTCODE_DEATH,	1.0,	0,	  0,	0,													BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
};


mmove_t MCowMoves[MMOVE_COW_SIZE]=
{
	//0
	{"std_i_n",					ACTCODE_STAND,	0,		 0,	  0,	ACTFLAG_LOOPANIM,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_w_n",					ACTCODE_MOVE,	1,		10,	-10,	ACTFLAG_LOOPANIM,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_s_rt",				ACTCODE_DEATH,	1,		0,	  0,	ACTFLAG_FULLANIM,													BBOX_PRESET_LAYSIDE,	0,		BODYPOS_UNKNOWN},
	{"std_imoo_n",				ACTCODE_STAND,	1,		0,	  0,	ACTFLAG_FULLANIM,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_ilooking_n",			ACTCODE_STAND,	1,		0,	  0,	ACTFLAG_FULLANIM,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
	{"std_p_n",					ACTCODE_STAND,	1,		0,	  0,	ACTFLAG_FULLANIM,													BBOX_PRESET_STAND,		0,		BODYPOS_UNKNOWN},
};
